version: '3'

services:

  db:
    container_name: prestashop_db
    volumes:
      - dbdata:/var/lib/mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_ROOT_USER: prestashop
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop-net
    ports:
      - 3306:3306


  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:latest # Latest stable version of the PrestaShop, to see all available images go to ...
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db:db
    ports:
      - 80:80
    volumes:
      - ./prestashop:/var/www/html
      - ./prestashop/modules:/var/www/html/modules
      - ./prestashop/themes:/var/www/html/themes
      - ./prestashop/override:/var/www/html/override
    environment:
      PS_DEV_MODE: 1
      PS_HOST_MODE: 0
      PS_DEMO_MODE: 1
      DB_SERVER: db
      DB_USER: prestashop
      DB_PASSWD: prestashop
      DB_PREFIX: ps_
      DB_NAME: prestashop
      PS_INSTALL_AUTO: 1
      PS_ERASE_DB: 0
      PS_INSTALL_DB: 0
      PS_LANGUAGE: fr
      PS_COUNTRY: FR
      PS_ALL_LANGUAGES: 0
      PS_FOLDER_ADMIN: admin
      PS_FOLDER_INSTALL: install
      PS_ENABLE_SSL: 0
      PS_DOMAIN: localhost:80
    networks:
      - prestashop-net

  phpmyadmin:
    # Spécifique mac M1
    #image: arm64v8/phpmyadmin
    image: phpmyadmin/phpmyadmin
    container_name: prestashop_phpmyadmin
    links:
      - db:db
    ports:
      - 8081:80
    depends_on:
      - db
    environment:
      - PMA_HOST:db
      - PMA_USER:prestashop
      - PMA_PASSWORD:prestashop
    restart: unless-stopped
    networks:
      - prestashop-net


networks:
  prestashop-net:
    driver: bridge

volumes:
  psdata:
  dbdata: